name: relaxdiego
description: Mark Maglana's Technical Blog
url: https://www.relaxdiego.com
enforce_ssl: www.relaxdiego.com
permalink: /:year/:month/:title.html
highlighter: rouge
markdown: kramdown
exclude:
  - .venv
  - tags
