#!/usr/bin/env bash

# Requires fswatch https://github.com/emcrisostomo/fswatch
# `brew install fswatch`

function render_resume {
    set -x
    asciidoctor-pdf --base-dir ./ resume/index.adoc
    mv resume/index.pdf resume.pdf
    asciidoctor --base-dir ./ resume/index.adoc
    { set +x; } 2>/dev/null
}

# This loop was inspired by https://superuser.com/a/181543/774060
fswatch -x ./resume |
while read -r path events; do
  if [ $(basename $path) = "resume.adoc" ]; then
      echo "Detected fsevent:"
      echo "   $(basename $path) $events"
      echo "Rendering resume:"
      render_resume
  fi
done
