#!/usr/bin/env bash

# Run this via `./start`

if hash foreman 2>/dev/null; then
    goreman start
else
    echo "==============================================="
    echo "Please install Goreman before proceeding:"
    echo "go get github.com/mattn/goreman"
    echo "==============================================="
fi
