== Mark Maglana, Software Engineer

[%hardbreaks]
(925) 558-5456
mmaglana@gmail.com
Pleasanton, CA


== Accomplishments

- *Developed Test Harnesses Frameworks* - I have built test harness frameworks in Ruby and Python. The type of test subjects I've built test frameworks for include web applications, CLI utilities, and network device software.

- *Built and Open Sourced API Libraries* - I have extensive experience writing client libraries for REST and other HTTP-related APIs. One of them is http://aviator.github.io/www/[Aviator], a Ruby library originally built for the OpenStack API but can be expanded to support other cloud providers.

- *Created an Agile Plugin for Redmine* - Redmine is an open software configuration management application. I built an agile plugin for it called Redmine Backlogs. These days, it is being maintained by a self-managing community at http://www.redminebacklogs.net and has also be forked by other projects such as https://www.openproject.org/features/agile-scrum/[OpenProject].

- *Built a Proof-of-Concept Domain Language* - I combined the things I liked about Cucumber and the Robot Framework into my own external domain specific language. This language reads like English (or any human language) and can be used to test itself. I consider this a hobby project that I use to learn about language design. The project is on https://github.com/ManaManaFramework/manamana[Github].


== Recent Projects

- *Open vSwitch Lab* - A Vagrant project that provisions two machines that talk over a simulated Internet. The lab is a companion project for the series of articles I wrote about http://www.relaxdiego.com/2014/09/ovs-lab.html[VXLAN], http://www.relaxdiego.com/2014/09/ovsdb.html[OVSDB], and http://www.relaxdiego.com/2014/09/hardware_vtep.html[the hardware VTEP schema]. link:https://github.com/relaxdiego/ovs-lab[Source in Github].

- *Aviator* - A lightweight Ruby client library for cloud REST APIs. I initially built this for the OpenStack API. My focus was to build a library that reflected, rather than obscured the underlying API. link:http://aviator.github.io/www/[Homepage].

- *Mana Mana* - A proof-of-concept business natural language testing framework that was inspired by Cucumber and the Robot framework. This was borne of my never-ending search for better ways to write maintainable automated tests. link:https://github.com/ManaManaFramework/manamana[Source in Github].

- *Proprietary OpenStack Dashboard* - A multi-tenant dashboard for OpenStack built on Ruby/Rails that had its own billing module which was built on top of OpenStack Ceilometer.

== Experience

*Software Engineer* (2014 - Present) +
Nexus IS (A Dimension Data Company), Pleasanton, CA

Nexus is a leading provider of professional, cloud, consulting and managed services for advanced IT solutions. Our team actively contributes to the OpenStack, Open vSwitch, and Open DayLight projects.

.*Achievements*

- Designed and implemented a framework for managing application lifecycle across cloud providers.

- Designed and implemented a test harness framework used by our testers for our various software products.

- Mentored and brought QA Engineers up to speed on testing our software products using the test harness framework.

- Designed and implemented various client libraries for various cloud APIs.


*Senior Director of Engineering* (2012 - 2014) +
Morph, Manhattan Beach, CA

Morph produced IaaS appliances that its customers can install inside of their data center to use as a springboard for quickly building their own cloud computing environment.

.*Achievements*

- Designed and developed a billing module for the product.

- Wrote a Ruby client library for the OpenStack API.

- Wrote a Cucumber-based integration test for the QA team.

- Mentored developers on proper software development practices.

- Helped set up the CI tools and process to ensure the main branch always has deployable, stable code.


*Software Product Manager* (2008 - 2012) +
Exist Global, Manila, Philippines

Exist provides tailored solutions, consulting and full cycle IT services to customers around the globe. At the time, I was assigned to Morph to help produce its cloud computing product.

.*Responsibilities*

- Oversaw the design and implementation of Morph AppSpace, one of the earliest Platform-as-a-Service providers in the market.

- Managed the product roadmap to ensure that requirements are prioritized properly and that they contain the right information.

- I helped Marketing Communications in their effort to generate product information for various marketing collateral.

- Implemented agile practices in Engineering to ensure timely delivery of stories and an overall coordinated effort of releases.

- Spearheaded the development of Redmine Backlogs (www.redminebacklogs.net). This allowed us to incorporate agile practices into our bug tracker while allowing us to retain control of our data.


*Systems Analyst/Programmer* (2003 - 2006) +
Deco Machine Shop, Davao City, Philippines

Deco Machine Shop, Inc. provides industrial machine fabrication services nationwide. Its major clients include Dole Philippines and San Miguel Corporation. As a systems analyst, my job was to understand the processes of the company and build software tools to automate parts of it. Software tools developed include a gear combination application which reduced a machinist’s work from one day to just under 10 minutes while increasing work precision.


*Systems Analyst/Programmer* (2002 - 2003) +
iThink Technologies, Davao City, Philippines

iThink provides business software and training solutions for major companies nationwide. Major clients include the Bangko Sentral ng Pilipinas, Meralco, and Davao Light and Power Company. I was involved as a systems analyst/programmer for the development of purchasing systems, HR systems, and other enterprise applications for iThink’s major customers. I also spearheaded the use of the Unified Modeling Language within the company and also provided some in-house training for a number of then upcoming technologies and development platforms.


*Web Developer* (2001 - 2002) +
Smartweb Philippines, Cebu City, Philippines

Smartweb was a US-based company with its production facility based in Cebu. It was involved in developing websites for small to medium sized businesses in the USA. I was a team leader in this organization. Apart from this, I also developed Smartweb’s employee time tracking and billing system, which later helped speed up the invoicing and employee time tracking for the company.


*Student Volunteer - Web Developer* (1997 - 2000)
University of San Carlos, Cebu City, Philippines

While attending college I was also a volunteer of the University of San Carlos Web Development Team which was tasked to build and maintain the university’s website. I was involved in the implementation in both the client side and the server side of the website and was later promoted to team leader. The team was, by then, composed of 10 student volunteers.



== Education

*Master of Management, Technology, Innovation, and Commercialization* 2007 +
The Australian National University

*Master of Management* 2006 +
University of the Philippines

*BS Computer Engineering* 2000 +
University of San Carlos


== Misc.

This resume is available online at http://www.relaxdiego.com/resume. Its source code may be found at https://github.com/relaxdiego/relaxdiego.github.com/blob/master/resume/resume.adoc.
