== Mark Maglana

[%hardbreaks]
mark.maglana@linux.com
https://relaxdiego.com
https://github.com/relaxdiego

I love building software and I've dedicated my career to mastering as many
of the art's numerous aspects. I've done this by taking on the various
challenges that come my way, learning as much as I can and delivering as best
as I can. Taking pride in the systems that I build. To this end, I have 
gained experience in:

- Entrepreneurship
- Technical Product Management
- Community Management
- Field Delivery
- DevOps
- Back-end Design and Development
- Front-end Design and Development


== Certifications

CNCF Certified Kubernetes Administrator +
Certificate ID: CKA-1700-0020-0100 +
(Expired Sep 2020 - Currently Renewing)

AWS Certified DevOps Engineer - Professional +
Certificate ID: T1M94XR2HNE4Q9G8


== Highlights

- *Designed and implemented the CI/CD platform for Tesla* -
I was hired by Tesla to build their CI/CD platform. I named the project
ATM (pronounced 'Adam'), conceptualized it with inputs from targetted
stakeholders, and implemented it using a combination of open-source and
built-from-scratch code. It continues to onboard in-house software to
this day and has become the de-facto CI/CD standard inside the company.

- *Produced a Kubernetes distribution for Teradata* -
Teradata needed a distribution of Kubernetes that catered to its very
specific needs. I mentored a team of DevOps engineers to produce this
internal distribution called KubeKit. I focused on equipping the team with
Scrum/Agile practices as well as a CI/CD platform allowing them to iterate
quickly and deliver a 1.0 release within 5 months.

- *Increased billing module accuracy and speed* -
When a former employer's billing module was producing inaccurate results,
I took on the task of debugging the problem. After finding the cause, I
introduced a number of fixes that improved the speed and accuracy of the
reports.

- *Contributed to the fast delivery of the Cisco 9K OVSDB plugin* -
Dimension Data needed to deliver an agent that allowed Cisco 9K switches to
work with VMware NSX. I volunteered to study the associated open standards
as well as the proprietary protocols for which we didn't have any documentation
at the time. I codified everything that I learned into a fully automated test
harness that became part of the team's CI/CD pipeline.

- *Talked at various meetups and conferences* - I've presented on various topics
such as https://relaxdiego.com/2017/11/sfk8s-lightning-talk.html[HA Kubernetes Outside the Cloud] (SF k8s Meetup 2017),
https://www.ansible.com/writing-fully-tested-ansible-modules-for-fun-and-profit[How 
to Write Fully-Tested Ansible Modules] (AnsibleFest NY 2016),
link:https://youtu.be/X5plV9kShsE[Deploying OpenShift with Ansible] (Internal talk 2016),
link:/2017/05/swampup-2017-slides.html[Baking and Frying Machine Images] (jFrog SwampUP Napa Valley 2017), 
https://www.openstack.org/summit/openstack-summit-atlanta-2014/session-videos/presentation/multi-node-devstack-with-puppet[Multi-node 
DevStack with Puppet] (OpenStack Summit Atlanta 2014), 
https://docs.google.com/presentation/d/18O8BVqNSCM5Q2x492AP9njom_l_CKJ_ak9SzNtQACV0/edit?usp=sharing[How 
I Built My Own BDD Framework] (Ruby on Rails Meetup, Los Angeles 2013), and
link:/2017/10/coding-kids.html[Introducing Scratch Programming] (2nd-grade Classroom 2017).

- *Reduced a 2-day manual process to 5 seconds* - While building the MIS for
a metal fabrication shop, I learned about a manual process that took shop floor
engineers 2 days to complete. After some research, I was able to build a
desktop app that reduced the computation time to 5 seconds.

- *Recipient of academic excellence award for best strategic plan* - I wanted
to understand the business of software and decided that focusing on the basics of
business management was key. I then applied for our state university's graduate
program for management where I was accepted. During the program, I was top of
class for Operations Management, Financial Management, and Business Strategy. I
then used everything that I learned to create a strategic plan for our family
business which resulted in me getting the academic excellence award for best
strategic plan.


== Experience

*Field Software Engineer (APAC Enterprise)*  (May 2019 - present) +
Canonical Services Ltd.

Canonical produces Ubuntu, provides commercial services for Ubuntu's users,
and works with hardware manufacturers, software vendors and cloud partners to
certify Ubuntu. My responsibilities range from developing software for automated
configuration management to on-site deployment of our products according to
customer requirements.

.*Achievements*

- Produced Kubernetes Operators for Grafana, Prometheus, and AlertManager
  using Juju, a Canonical product for automating the provisioning and configuration
  of servers and containers. The three operators are able to automatically
  connect to each other via Juju's relations functionality. https://www.youtube.com/watch?v=oqiWEUImCz4[Demo Video]

- Delivered https://maas.io/[MAAS], OpenStack, and https://ubuntu.com/kubernetes[Charmed Kubernetes] in various
  customer sites.

- Produced an internal guide for validating a customer's existing Kubernetes
  Cluster that was installed using Kubespray/Kubeadm.

- Produced a beginner's guide for developing a Python-based Kubernetes
  Operator for those just getting started with Kubernetes Operators. https://www.youtube.com/watch?v=lsuW9XGWosQ[Video]

- Produced demo videos for pre-sales purposes that highlights the features of
  Kubernetes. https://www.youtube.com/watch?v=OZfuAi112bs[Video].

- Produced a guide for colleagues about proper Python dependency management.
  https://www.youtube.com/watch?v=aWVzR296XcU[Video].

- Produced a video for the benefit of those who are just starting with Juju
  Charms development. https://www.youtube.com/watch?v=LckY8fdJL40[Video]

- Produced a tool that allows DevOps Engineers to work together on the same
  remote terminal. Especially useful for situations where a team needs to debug
  a server collectively. https://github.com/relaxdiego/coterminal[Github Repo]


*President, Co-founder* (Nov 2018 - Dec 2020) +
Amplify Inc., Philippines

Amplify Inc (amplifyinc.ph) was an SEC-registered corporation that aimed to
accelerate the Philippines' digital transformation. It specialized in the
design and delivery of building auxiliary systems such as Fire Detection and
Alarm Systems; Local Area Networking; Wireless Design and implemention; as
well as Building Management Systems.

.*Achievments*

- Assembled a board of directors to oversee the direction of the company. The
  board was composed of a former IT manager, an electronics and communications
  engineer, and a certified public accountant.

- Built the company from the ground up with proper support for sales and engineering.
  Both departments synced up twice weekly via stand ups and a shared task board.
  All communications were logged in a sales database that allowed sales and engineering
  to stay synchronized.

- Achieved a decent rise in revenue in its first year to be nearly self sustaining
  within a year but was hit hard by the pandemic and lock downs just when it was
  about to break even.


*Senior Staff DevOps Engineer* (Dec 2017 - Oct 2018) +
Tesla, Fremont, CA

Tesla's mission is to accelerate the world's transition to sustainable energy.

.*Achievements*

- Designed and implemented a CI/CD platform that software engineers used for their
  applications. They onboarded their projects via a declarative YAML file that they
  commit with their code. The platform provided services such as (1) container image
  build and publish, (2) Unit, integration, and black box testing, (3) static code
  analysis, (4) chat notifications, (5) build health dashboards, (6) auto-DB migration,
  and (7) blue-green deployments to Kubernetes. The project has since matured to have
  a internal community of contributors as well as a collection of over 600 services
  being managed.


*DevOps Engineer* (Nov 2016 - Dec 2017) +
Teradata, Santa Clara, CA

Teradata Corporation is a Fortune 1000 provider of data warehouse platforms,
software and services. Our team is at the center of the company's thrust to
build modern data analytics products around Teradata's traditional offerings.


.*Achievements*

- Team Lead for the internal Kubernetes distribution project called KubeKit. This
  project is a core critical component of all the microservices-based products
  that Teradata is building. I led the team, provided product requirements
  guidance, wrote code, as well as oversaw the internal community management
  aspects that were necessary to onboard the various products and programs on
  top of the project. I also worked on growing the team such that it can
  support all the Kubernetes requirements of the aforementioned Teradata products.
 
- I functioned as the DevOps Engineer for the AppCenter project where I was
  responsible for guiding the architecture of the team’s software manufacturing
  pipeline. I designed the pipeline and also did the initial implementation. I
  later served as an adviser/mentor to the team members that were implementing
  the rest of the design. This software manufacturing pipeline is critical in
  ensuring the timely delivery and quality of AppCenter which is a central
  component of Teradata's UDA program.
 
- I was a member of Teradata's internal DevOps Technology Council. This council
  is tasked to collate, curate, and evangelize the DevOps best practices across
  Teradata to improve its Engineering operational efficiency and effectiveness.
  I was assigned to the “standardized processes” component of the framework that
  the council is building.
 

*QA/Release Engineer* (Jan 2014 - Sep 2016) +
Dimension Data, Pleasanton, CA

Dimension Data is a leading provider of professional, cloud, consulting 
and managed services for advanced IT solutions. Our team actively 
contributed to Ansible, OpenStack, Open vSwitch, and Open DayLight. My
official title was QA/Release Engineer but my responsibilities spanned
those of a software engineer/architect.

.*Achievements*

- Designed and implemented a non-interactive agent that automatically 
  launched time-bound AWS spot instances as needed for use as auxiliary 
  Jenkins workers that handled non-time-critical builds.

- Wrote Ansible modules to be used for provisioning resources on Dimension
  Data's cloud service.

- Developed an Ansible-based project that deployed an HA OpenShift
  PoC for our CI/CD pipeline.

- Designed and implemented the full stack of a web application that was
  designed to transform data from one format to another. The system used
  Rails, Postgres, Redis (for job queueing), Resque, and Ceph both for
  persistent block and object storage.

- Designed and implemented the automated test harness for the N9K OVSDB
  plugin for NSX.

- Designed and implemented the link:https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/white-paper-c11-740091.html#_Toc517769218[Cisco N9K OVSDB plugin CLI utility].

- Mentored development teams in new technologies, standards, and even
  3rd-party protocols that they needed to incorporate or interface to. This
  allowed them to hit the ground running and deliver within budget.


*Senior Director Of Engineering* (Jul 2012 - Jan 2014) +
Morph, Manhattan Beach, CA

Morph (a sister company of Exist Global) was the first PaaS built on top
of AWS and later on pivoted to providing IaaS appliances that its customers
can install inside of  their data center to use as a springboard for quickly
building their own cloud computing environment. My official title was Senior Director of
Engineering but my actual roles spanned that of a software engineer/architect.

.*Achievements*

- Designed and developed a billing module for the product.

- Wrote a Ruby client library for the OpenStack API.

- Wrote a Cucumber-based integration test for the QA team.

- Mentored developers on proper software development practices.

- Helped set up the CI tools and process to ensure the main branch always
has deployable, stable code.


*Senior Director for Product Development* (Jan 2008 - Jul 2012) +
Exist Global, Manila, Philippines

Exist provides tailored solutions, consulting and full cycle IT services to
customers around the globe. At the time, I was assigned to Morph to help
produce its cloud computing product.

.*Responsibilities*

- Oversaw the design and implementation of Morph AppSpace, one of the earliest
Platform-as-a-Service providers built on top of AWS in the market.

- Managed the product roadmap to ensure that requirements are prioritized
properly and that they contain the right information.

- I helped Marketing Communications in their effort to generate product
information for various marketing collateral.

- Implemented agile practices in Engineering to ensure timely delivery of
stories and an overall coordinated effort of releases.


*Systems Analyst/Programmer* (Mar 2003 - Dec 2006) +
Deco Machine Shop, Davao City, Philippines

Deco Machine Shop, Inc. provides industrial machine fabrication services
nationwide. Its major clients include Dole Philippines and San Miguel
Corporation. As a systems analyst, my job was to understand the processes
of the company and build software tools to automate parts of it. Software
tools developed include a gear combination application which reduced a
machinist’s work from one day to just under 5 seconds while increasing
work precision.

In 2007, I took a year off to obtain my second Master's degree.


*Systems Analyst/Programmer* (Jan 2002 - Jan 2003) +
iThink Technologies, Davao City, Philippines

iThink provides business software and training solutions for major companies
nationwide. Major clients include the Bangko Sentral ng Pilipinas, Meralco,
and Davao Light and Power Company. I was involved as a systems analyst/programmer
for the development of purchasing systems, HR systems, and other enterprise
applications for iThink’s major customers. I also spearheaded the use of the
Unified Modeling Language within the company and also provided some in-house
training for a number of then upcoming technologies and development platforms.


*Web Developer* (Jan 2001 - Jan 2002) +
Smartweb Philippines, Cebu City, Philippines

Smartweb was a US-based company with its production facility based in Cebu.
It was involved in developing websites for small to medium sized businesses
in the USA. I was a team leader in this organization. Apart from this, I also
developed Smartweb’s employee time tracking and billing system, which later
helped speed up the invoicing and employee time tracking for the company.


*Student Volunteer - Web Developer* (Jun 1997 - Oct 2000) +
University of San Carlos, Cebu City, Philippines

While attending college I was also a volunteer of the University of San Carlos
Web Development Team which was tasked to build and maintain the university’s
website. I was involved in the implementation in both the client side and the
server side of the website and was later promoted to team leader. The team was,
by then, composed of 10 student volunteers.



== Education

*Master of Management, Technology, Innovation, and Commercialization* +
Jan 2007 - Dec 2007 +
The Australian National University +
Acton, Canberra ACT 2601, Australia

*Master of Management* +
May 2004 - Apr 2006 +
University of the Philippines - School of Management +
Mintal, Davao City 8022, Philippines

*BS Computer Engineering* Jun 1995 - Oct 2000 +
University of San Carlos +
P. del Rosario Street, Cebu City 6000, Philippines


== A Few LinkedIn Recommendations

> When I joined Tesla and understood the problems we needed to solve
> around CI/CD I immediately thought of Mark and the work we did together
> at Dimension Data. Mark did amazing work for us at Tesla building an
> entirely new pipeline in just a few months. He worked with Developers,
> QA and IT OPS to ensure what he was building could be supported and useful.
> It is always a pleasure working with Mark. The team here still misses him!
> -- Mike Outland, Sr. DevOps Manager at Tesla

> Mark is a world class software professional and DevOps craftsman. He is
> a rare combination of somebody who can elegantly operate across the spectrum
> ranging from the toughest implementation detail all the way to
> thought-leadership and evangelism. Mark is the kind of professional you can
> entrust with a problem statement in its most abstract form and step back,
> assured that the solution will be built with cutting-edge technology choices
> and delivered on time. It's always a pleasure to work with Mark knowing he
> can be your go-to-person, an advisor and leader in his field, and an evangelist
> aware of where the industry is going.
> -- Chai Atreya, Head of Engineering at Teradata

> Mark is an exceptionally capable software architect and developer. 
> When a new technology or language needed to be implemented, Mark 
> was able to obtain a deep level of understanding in a very short 
> amount of time. I have seen him architect and implement everything 
> from full APIs to cloud middleware to full front-ends. Over the 
> years he has gained a wide breadth of knowledge in everything 
> cloud & container. Working with him has been regularly humbling 
> and wonderfully educational. Beyond his technical prowess, Mark 
> is also very fun to work with and mentors people exceptionally well. 
> He uses his great sense of humor to take the stress out of tough 
> challenges and motivate teams to push on. I give Mark my highest 
> recommendation to anything he wants to take on. He will be a rare 
> gift to the next company he works with.
> -- Aimon Bustardo, Lead DevOps Engineer, SalesForce.com

> Mark was one of my favorite people to work with at Teradata — the
> energy he brings to the projects and teams he works with is infectious.
> Mark's leadership style stems not only from his energy, but his
> expertise as a DevOps Engineer. He is respected by colleagues at all
> levels and is a huge asset for any modern engineering organization.
> -- Tim McIntire, VP Shared Services, Teradata

> Mark is one of the few people I know who can truly perform well in
> a player/coach role. While his technical chops may be second to
> none, he combines those chops with a natural ability to lead from
> the front. He would most certainly be a valuable asset to any team
> lucky enough to have him.
> -- Jason Reslock, Senior DevOps Manager, SalesForce.com

> Possibly the best reason I looked forward to going to work everyday 
> is because of the opportunity to work closely and be mentored by
> Mark. I see him as a true software craftsman who is passionate about
> code and cares a lot about code quality, readability and testability.
> He can lead teams, mentor teammates, commit production code within
> time and budget while giving a helping hand with whatever is the issue
> of the day.
> -- Bert Diwa, Software Engineer in Test, CrowdStrike

> [Mark] produced solid designs. He was an expert at Python (and 
> apparently Ruby too). He seemed to know about every Open Source 
> project out there. His mastery of all things Git and GitHub were 
> critical support to several of us who had never used Git before. 
> All in all, Mark was an invaluable resource to the project and 
> to the team. He seemed to get his dozen projects done in time 
> while simultaneously providing whatever technical support was 
> being asked of him by the team.
> -- Jay Riddell, Sr. Web Designer, Davis Instruments

> Mark was a particularly able and focused student, capable of 
> working independently and evaluating ideas and approaches 
> critically. His particular interest at the time [while studying at
> the Australian National University] was the role, design and
> development of business incubators as a tool for regional development.
> -- Don Scott-Kemmis, Innovation Policy Consultant


== All Resume Formats

* https://relaxdiego.com/resume[HTML]
* https://relaxdiego.com/resume.pdf[PDF]
* https://raw.githubusercontent.com/relaxdiego/relaxdiego.github.com/master/resume/resume.adoc[AsciiDoc]
