== Mark Maglana, DevOps Engineer

[%hardbreaks]
(925) 558-5456
mark@maglana.com

I have a strong software development background with specialization
in backend design and implementation. I like to get down and dirty with
the technical aspects of a project, learn something new everyday, and
to apply that knowledge at work. More than that, I enjoy getting stuff done!


== Accomplishments

- *Increased Module Accuracy and Speed by at Least 10x* - I offered  to
re-design and re-implement a cloud computing application's billing module
which was producing incomplete results and regularly timing out before it
could even display half of an account's report. After I redesigned it, the
reports were displayed immediately, and the amounts were 100% accurate.

- *Was Into Containerization Before It was famous!* - I have been following
  containerization since the initial Docker days even though it was outside
  my assignment. Through my ongoing curiousity, I was able to build an
  HA OpenShift environment as a means to replace our internal CI/CD pipeline.

- *Facilitated Timely Delivery of Software By Automating Requirements* - My
employer needed to deliver an autonomous software agent for a customer. I
offered to study the associated open standards and proprietary protocols to
learn about the complete requirements. I then codified these requirements in
an application that developers can execute against their code to give them
instant feedback. The application later also served as a regression test
harness allowing the team to deliver the software on time and within budget.

- *Reduced a 2-day Manual Process to 5-seconds* - While building the MIS for
a metal fabrication shop, I learned about a manual computation process that
took shop floor engineers 2 days to complete. After some research and a few
questions on a compsci newsgroup, I was able to build a desktop app that reduced
the computation time to 5 seconds.

- *Improved Requirements Gathering Through Prototyping* - Upon joining a new
software consulting firm, I noticed the long feedback loop from requirements
gathering to user testing. I encouraged and guided my teammates to adopt
prototyping as one of the ways to improve requirements gathering and reduce
waste. The results were positive and the engineers along with the users were
very happy with the results.

- *Recipient of Academic Excellence Award for Best Strategic Plan* - I wanted
to understand the business of software and decided that focusing on the basics of
business management was key. I then applied for our state university's graduate
program for management where I was accepted. During the program, I was top of
class for Operations Management, Financial Management, and Business Strategy. I
then used everything that I learned to create a strategic plan for our family
business which resulted in me getting the strategic plan award.

== A Few Open Source Projects

- *Open vSwitch Lab* - A Vagrant project that provisions two machines that talk
over a simulated Internet. The lab is a companion project for the series of
articles I wrote about http://www.relaxdiego.com/2014/09/ovs-lab.html[VXLAN], http://www.relaxdiego.com/2014/09/ovsdb.html[OVSDB], and http://www.relaxdiego.com/2014/09/hardware_vtep.html[the hardware VTEP schema]. link:https://github.com/relaxdiego/ovs-lab[Source in Github].

- *Aviator* - A lightweight Ruby client library for cloud REST APIs. I initially
built this for the OpenStack API. My focus was to build a library that reflected,
rather than obscured the underlying API. link:http://aviator.github.io/www/[Homepage].

- *Mana Mana* - A proof-of-concept business natural language testing framework
that was inspired by Cucumber and the Robot framework. This was borne of my
never-ending search for better ways to write maintainable automated tests. link:https://github.com/ManaManaFramework/manamana[Source in Github].


== One More Thing

Coding without tests is like driving a car without seatbelts so I always make
sure to cover my code with a reasonable amount of tests. Here's 
https://www.relaxdiego.com/2015/11/my-dev-setup-part-3.html[how I work].

== Experience

*DevOps Engineer* (Jan 2014 - Sep 2016) +
Dimension Data, Pleasanton, CA

Dimension Data is a leading provider of professional, cloud, consulting 
and managed services for advanced IT solutions. Our team actively 
contributes to Ansible, OpenStack, Open vSwitch, and Open DayLight.

.*Achievements*

- Developed an Ansible-based project that deployed an HA OpenShift
  platform for use by our team as a replacement for our CI/CD pipeline.

- Designed and implemented the full stack for a web application that was
  designed to transform data from one format to another.

- Designed and implemented an automated test harness framework used by 
our testers for our various software products.

- Designed and implemented various client libraries for various cloud APIs.

- Designed and implemented a framework for managing application lifecycle
across cloud providers.

- Studied new technologies and standards for an internal project thereby
  helping the project team hit the ground running and deliver within
  their specified deadline.


*Senior Director of Engineering* (Jul 2012 - Jan 2014) +
Morph, Manhattan Beach, CA

Morph produced IaaS appliances that its customers can install inside of 
their data center to use as a springboard for quickly building their own 
cloud computing environment.

.*Achievements*

- Designed and developed a billing module for the product.

- Wrote a Ruby client library for the OpenStack API.

- Wrote a Cucumber-based integration test for the QA team.

- Mentored developers on proper software development practices.

- Helped set up the CI tools and process to ensure the main branch always
has deployable, stable code.


*Software Product Manager* (Jan 2008 - Jul 2012) +
Exist Global, Manila, Philippines

Exist provides tailored solutions, consulting and full cycle IT services to
customers around the globe. At the time, I was assigned to Morph to help
produce its cloud computing product.

.*Responsibilities*

- Oversaw the design and implementation of Morph AppSpace, one of the earliest
Platform-as-a-Service providers in the market.

- Managed the product roadmap to ensure that requirements are prioritized
properly and that they contain the right information.

- I helped Marketing Communications in their effort to generate product
information for various marketing collateral.

- Implemented agile practices in Engineering to ensure timely delivery of
stories and an overall coordinated effort of releases.

- Spearheaded the development of Redmine Backlogs (www.redminebacklogs.net).
This allowed us to incorporate agile practices into our bug tracker while
allowing us to retain control of our data.


*Systems Analyst/Programmer* (Mar 2003 - Dec 2006) +
Deco Machine Shop, Davao City, Philippines

Deco Machine Shop, Inc. provides industrial machine fabrication services
nationwide. Its major clients include Dole Philippines and San Miguel
Corporation. As a systems analyst, my job was to understand the processes
of the company and build software tools to automate parts of it. Software
tools developed include a gear combination application which reduced a
machinist’s work from one day to just under 5 seconds while increasing
work precision.

In 2007, I took a year off to obtain my second Master's degree.


*Systems Analyst/Programmer* (Jan 2002 - Jan 2003) +
iThink Technologies, Davao City, Philippines

iThink provides business software and training solutions for major companies
nationwide. Major clients include the Bangko Sentral ng Pilipinas, Meralco,
and Davao Light and Power Company. I was involved as a systems analyst/programmer
for the development of purchasing systems, HR systems, and other enterprise
applications for iThink’s major customers. I also spearheaded the use of the
Unified Modeling Language within the company and also provided some in-house
training for a number of then upcoming technologies and development platforms.


*Web Developer* (Jan 2001 - Jan 2002) +
Smartweb Philippines, Cebu City, Philippines

Smartweb was a US-based company with its production facility based in Cebu.
It was involved in developing websites for small to medium sized businesses
in the USA. I was a team leader in this organization. Apart from this, I also
developed Smartweb’s employee time tracking and billing system, which later
helped speed up the invoicing and employee time tracking for the company.


*Student Volunteer - Web Developer* (Jun 1997 - Oct 2000) +
University of San Carlos, Cebu City, Philippines

While attending college I was also a volunteer of the University of San Carlos
Web Development Team which was tasked to build and maintain the university’s
website. I was involved in the implementation in both the client side and the
server side of the website and was later promoted to team leader. The team was,
by then, composed of 10 student volunteers.



== Education

*Master of Management, Technology, Innovation, and Commercialization* +
Jan 2007 - Dec 2007 +
The Australian National University +
Acton, Canberra ACT 2601, Australia

*Master of Management* +
May 2004 - Apr 2006 +
University of the Philippines - School of Management +
Mintal, Davao City 8022, Philippines

*BS Computer Engineering* Jun 1995 - Oct 2000 +
University of San Carlos
P. del Rosario Street, Cebu City 6000, Philippines


== Misc.

This resume is available online at https://www.relaxdiego.com/resume. Its
source code may be found at https://github.com/relaxdiego/relaxdiego.github.com/blob/master/resume/resume.adoc.
The latest PDF is always at https://www.relaxdiego.com/resume.pdf
