#!/usr/bin/env bash

# In case something changed before this script started
make resume

# Requires fswatch https://github.com/emcrisostomo/fswatch
# `brew install fswatch`

# This loop was inspired by https://superuser.com/a/181543/774060
fswatch -x ./resume ./resumex |
while read -r abspath events; do
  relpath=${abspath#$(pwd)/}
  filename=$(basename "$abspath")
  extension="${filename##*.}"

  if [ "$extension" = "adoc" ]; then
      echo "Source file changed: $relpath"
      make resume
  fi
done
