#!/usr/bin/env bash
set -euo pipefail

# Requires fswatch https://github.com/emcrisostomo/fswatch
# `brew install fswatch`

# This loop was inspired by https://superuser.com/a/181543/774060
exec fswatch \
    --recursive \
    --latency 1 \
    --event-flags \
    --recursive \
    ./_includes/code-snippets |
    while read -r abspath events; do
        relpath="${abspath#$(pwd)/}"
        filename="$(basename "$abspath")"
        extension="${filename##*.}"
        if [ "$extension" = "py" ]; then
            echo "Snippetd   : $relpath"
            echo "Events     : $events"
            echo "Python path: $(which python)"
            echo "Python ver : $(python --version)"
            if ! python "$relpath"; then
                RED='\033[0;31m'
                NC='\033[0m'
                echo -e "${RED}Snippet execution failed${NC}"
            fi
        fi
    done
